name: Deploy Static Site

on:
  schedule:
    - cron: "0 6 * * *" # Runs daily at 6 AM UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-site:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4

      - name: 🔥 Cache Bun Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: 🚀 Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 📦 Install Dependencies
        run: bun install --silent

      - name: 🚀 Push `index.html` to `jasonnathan.github.io`
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # Clone the GitHub Pages repo directly
          git clone --depth=1 https://github.com/jasonnathan/jasonnathan.github.io.git gh-pages
          cd gh-pages          
          git switch gh-pages
          
          # Move updated index.html
          cp ../index.html ./

          # Set Git identity (Fixes "Please tell me who you are" error)
          git config --global user.name "Jason Nathan"
          git config --global user.email "jjnathanjr@gmail.com"

          git add index.html
          git commit -m "🚀 Update index.html from README" || echo "No changes to commit"

          # Authenticate and push securely
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/jasonnathan/jasonnathan.github.io.git
          git push origin HEAD

