name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Fetch Repository Contents"
        uses: actions/checkout@main

      - name: "📚 Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: 'jasonjnathan'  # Your Hashnode Username
          BLOG_URL: 'https://geekist.co'  # Explicitly set your blog URL
          COUNT: 5  # Number of latest posts
          STYLE: "blog-right"  # Change this to another style if needed
          FILE: "README.md"  # Updates your GitHub profile README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
