name: Update GitHub Profile with Hashnode Post

on:
  repository_dispatch:
    types: [hashnode_post_published]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install node-fetch

      - name: Update README
        env:
          HASHNODE_SECRET: ${{ secrets.HASHNODE_SECRET }}
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
          SIGNATURE_HEADER: ${{ github.event.client_payload.headers['x-hub-signature-256'] }}
        run: node updateArticles.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with new Hashnode post"
          git push
