name: Update GitHub Profile with Hashnode Post

on:
  repository_dispatch:
    types: [hashnode_post_published]

jobs:
  update-articles:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun install
      - name: Update README
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
          SIGNATURE_HEADER: ${{ github.event.client_payload.headers['x-hub-signature-256'] }}
        run: bun updateArticles.ts

      - name: Commit and push changes
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'Jason Nathan'
          git config --global user.email 'jjnathanjr@gmail.com'
          git add README.md
          git commit -m "Update README with new Hashnode post" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main